In [64]:
skill = "CBD"
skill_trees = ["BACDE", "CBADF", "AECB", "BDA"]

def solution(skill, skill_trees):   
    answer = 0
    
    for sk_tr in skill_trees:
        print("1 : ", sk_tr)
        skill_list = list(skill)
        print("2 : ", skill_list)
        
        for ch in sk_tr:
            print("3 : ", skill_list)
            print("4 : ", ch)
            if ch in skill:
                if ch != skill_list.pop(0):
                    break
        else:
            print("5 : ", sk_tr)
            answer += 1
    return answer

print(solution(skill, skill_trees))

1 :  BACDE
2 :  ['C', 'B', 'D']
3 :  ['C', 'B', 'D']
4 :  B
1 :  CBADF
2 :  ['C', 'B', 'D']
3 :  ['C', 'B', 'D']
4 :  C
3 :  ['B', 'D']
4 :  B
3 :  ['D']
4 :  A
3 :  ['D']
4 :  D
3 :  []
4 :  F
5 :  CBADF
1 :  AECB
2 :  ['C', 'B', 'D']
3 :  ['C', 'B', 'D']
4 :  A
3 :  ['C', 'B', 'D']
4 :  E
3 :  ['C', 'B', 'D']
4 :  C
3 :  ['B', 'D']
4 :  B
5 :  AECB
1 :  BDA
2 :  ['C', 'B', 'D']
3 :  ['C', 'B', 'D']
4 :  B
2


In [6]:
index_list = []
for ch in "BACDE":
    index_list.append(skill.find(ch))
index_list

[1, -1, 0, 2, -1]

In [21]:
print(range(10))

range(0, 10)


In [26]:
class idontknow:
    def __init__(self):
        print("idontknow init")
    def __str__(self):
        return "idontknow str"
    def __repr__(self):
        return "idontknow repr"

udontknow = idontknow()
print(udontknow)
udontknow

idontknow init
idontknow str


idontknow repr

In [31]:
import numpy as np
from numpy.random import randn

In [33]:
data = randn(2,3)
data

array([[ 1.05776813,  1.04922301, -1.14037553],
       [-0.24134763, -0.3390147 ,  0.63149878]])

In [34]:
data * 10

array([[ 10.57768132,  10.49223008, -11.40375531],
       [ -2.41347633,  -3.39014698,   6.31498784]])

In [35]:
data + 10

array([[11.05776813, 11.04922301,  8.85962447],
       [ 9.75865237,  9.6609853 , 10.63149878]])

In [36]:
data + data

array([[ 2.11553626,  2.09844602, -2.28075106],
       [-0.48269527, -0.6780294 ,  1.26299757]])

In [37]:
data.shape

(2, 3)

In [38]:
data1 = randn(2,3)
data2 = randn(2,3)
print(data1, data2)

[[ 0.87394213 -0.80299943  1.86364317]
 [-0.34687978  0.25994859  0.3749387 ]] [[-0.96344974  0.6185389  -1.15465386]
 [-0.52518887  1.01848117  0.33735895]]


In [39]:
data1 * data2

array([[-0.84199931, -0.49668639, -2.15186279],
       [ 0.1821774 ,  0.26475274,  0.12648893]])

In [40]:
np.dot(data1, data2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [41]:
data3 = np.arange(6).reshape(2,3)
data3

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
data3.shape

(2, 3)

In [43]:
data4 = np.array([1,2])
data4

array([1, 2])

In [44]:
data4.shape

(2,)

In [45]:
data4 = np.array([[1,2]])
data4

array([[1, 2]])

In [46]:
data4.shape

(1, 2)

In [47]:
data4 = np.array([[1],[2]])
data4

array([[1],
       [2]])

In [48]:
data4.shape

(2, 1)

In [51]:
print(np.arange(6))
data3 = np.arange(6).reshape(2,3)
data3.shape
print(data3)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [52]:
data3_3d = data3[:, np.newaxis, :]
data3_3d.shape

(2, 1, 3)

In [53]:
data3_3d

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [54]:
data3_3d = data3[:, :, np.newaxis]
data3_3d.shape

(2, 3, 1)

In [55]:
data3_3d

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [65]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [67]:
arr[[1,2,3],[1,2,3]]

array([ 5, 10, 15])

In [68]:
arr[[1,2,3]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
arr[[-1,-2,-3]]

array([[28, 29, 30, 31],
       [24, 25, 26, 27],
       [20, 21, 22, 23]])

In [71]:
arr1 = np.arange(24).reshape(2,3,4)
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
arr1[0,0,:]

array([0, 1, 2, 3])

In [76]:
arr1[0,1,:]

array([4, 5, 6, 7])

In [73]:
arr2 = arr1.transpose(1,0,2)
print(arr2.shape)
arr2

(3, 2, 4)


array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [77]:
arr2[0,0,:]

array([0, 1, 2, 3])

In [78]:
arr2[1,0,:]

array([4, 5, 6, 7])

In [79]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [82]:
np.sqrt(arr1)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])